name: build
on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches: ["*"]
    paths:
      - .github/workflows/build.yml
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          diagnostic-endpoint: ""

      - uses: cachix/cachix-action@v17
        with:
          name: wahoo-wahoo-man
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: |
          mkdir -p ~/.config/nixpkgs
          echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix

      - run: |
          echo -n "${{ secrets.URL }}" > url.txt
          echo -n "${{ secrets.HASH }}" > hash.txt
          git add *.txt --intent-to-add
          git update-index --skip-worktree --assume-unchanged *.txt

      - name: build-package
        id: build-package
        run: |
          set -euxo pipefail
          nix build .#sm64ex-ap -L --no-link --print-out-paths | cachix push wahoo-wahoo-man

      - run: |
          rm hash.txt
          rm url.txt
          git rm *.txt
